export const apiKey = '9b6b424f000143109c4120743231105';

export const weatherImages = {
  'Sunny': require('../assets/images/sunny.png'),
  'Clear': require('../assets/images/sunny.png'),
  'Partly cloudy': require('../assets/images/partlycloudy.png'),
  'Overcast': require('../assets/images/cloudy.png'),
  'Cloudy': require('../assets/images/cloudy.png'),
  'Moderate rain': require('../assets/images/rain.png'),
  'Patchy rain possible': require('../assets/images/rain.png'),
  'Light rain': require('../assets/images/rain.png'),
  'Light rain shower': require('../assets/images/rain.png'),
  'Moderate rain at times': require('../assets/images/rain.png'),
  'Light drizzle': require('../assets/images/rain.png'),
  'Heavy rain': require('../assets/images/heavyrain.png'),
  'Heavy rain at times': require('../assets/images/heavyrain.png'),
  'Moderate or heavy rain shower': require('../assets/images/heavyrain.png'),
  'Moderate or heavy rain with thunder': require('../assets/images/heavyrain.png'),
  'Moderate or heavy freezing rain': require('../assets/images/snow.png'),
  'Light sleet': require('../assets/images/snow.png'),
  'Light snow': require('../assets/images/snow.png'),
  'Moderate snow': require('../assets/images/snow.png'),
  'Heavy snow': require('../assets/images/snow.png'),
  'Patchy light snow': require('../assets/images/snow.png'),
  'Mist': require('../assets/images/fog.png'),
  'Fog': require('../assets/images/fog.png'),
  'other': require('../assets/images/fog.png')
}

export const weatherImagesNight = {
  'Sunny': require('../assets/images/clear_night.png'),
  'Clear': require('../assets/images/clear_night.png'),
  'Partly cloudy': require('../assets/images/partlycloudy_night.png'),
  'Overcast': require('../assets/images/cloudy.png'),
  'Cloudy': require('../assets/images/cloudy.png'),
  'Moderate rain': require('../assets/images/rain.png'),
  'Patchy rain possible': require('../assets/images/rain.png'),
  'Light rain': require('../assets/images/rain.png'),
  'Light rain shower': require('../assets/images/rain.png'),
  'Moderate rain at times': require('../assets/images/rain.png'),
  'Light drizzle': require('../assets/images/rain.png'),
  'Heavy rain': require('../assets/images/heavyrain.png'),
  'Heavy rain at times': require('../assets/images/heavyrain.png'),
  'Moderate or heavy rain shower': require('../assets/images/heavyrain.png'),
  'Moderate or heavy rain with thunder': require('../assets/images/heavyrain.png'),
  'Moderate or heavy freezing rain': require('../assets/images/snow.png'),
  'Light sleet': require('../assets/images/snow.png'),
  'Light snow': require('../assets/images/snow.png'),
  'Moderate snow': require('../assets/images/snow.png'),
  'Heavy snow': require('../assets/images/snow.png'),
  'Patchy light snow': require('../assets/images/snow.png'),
  'Mist': require('../assets/images/fog.png'),
  'Fog': require('../assets/images/fog.png'),
  'other': require('../assets/images/fog.png')
}